with TRANSACTIONS as(
select ORDER_ID ,
	LINE_ID ,
	TYPE ,
	DT ,
	POS_SITE_ID ,
	SKU_ID,
	FSCLDT_ID,
	PRICE_SUBSTATE_ID,
	SALES_UNITS ,
	SALES_DOLLARS ,
	DISCOUNT_DOLLARS,
	ORIGINAL_ORDER_ID,
	ORIGINAL_LINE_ID
from retail_db.public.TRANSACTIONS
)

select * from TRANSACTIONS
